### ISSUE TITLE
Add a banner/alert on Shell fishing closures

### ISSUE THREAD

**Issue by mrun0205** [WHOIGit/whoi-hab-hub#24]
Is there a way to add a an alert when selecting Shellfish closures that says that the closure data on the HABHUB website may not be up to date and have a link to the pertinent State's  Maine DMR/Massachusetts DMR to get latest Shellfish closure data for the site?
E.g.
"Closure data on this website may not be up to date. For most accurate shellfish closure data for this site please visit:
https://www.maine.gov/dmr/shellfish-sanitation-management/closures/index.html"

"Closure data on this website may not be up to date. For most accurate shellfish closure data for this site please visit:
https://www.mass.gov/lists/emergency-shellfish-closure-and-opening-notices"

**Comment by mbrosnahan** [comment]
Or just add "See links" to message on map, then add DMF, DMR and DES pages for up-to-date closure information in the links menu?
