### ISSUE TITLE
View in full screen not functioning

### ISSUE THREAD

**Issue by kalimhorn** [WHOIGit/whoi-hab-hub#6]
<img width="1440" alt="Screen Shot 2021-01-05 at 10 35 36 AM" src="https://user-images.githubusercontent.com/73716251/103666317-7c7dff00-4f42-11eb-8f00-88babce42bc6.png">
 
The drop down on the graphs only makes the background go away - graph stays the same size

**Comment by ethanandrews** [comment]
replaced with custom window expansion
